### ISSUE TITLE
`extract_pdf` returns an error when `gmm_components != 2`

### ISSUE THREAD

**Issue by imariasantos** [andreatramacere/primal#3]
In the Primal core tutorial notebook, when calling the function `extract_pdf`, if the value passed for `gmm_components` is not `2`, then the function raises a ValueError.

```
pdf_matrix=extract_pdf(ada_boost_model, test, gmm_components=3, out_file_name='ada_boost_pdf.fits')
```
returns

```
ValueError: could not broadcast input array from shape (2) into shape (3)
```

**Comment by andreatramacere** [comment]
Hi Imara,
I have merged your change, is this fixing completely the issue?
Cheers
  Andrea

**Comment by imariasantos** [comment]
Hello,
This fixes the issue, yes.
Cheers !

**Comment by andreatramacere** [comment]
Ok,
thanks!
I close the issue then.
Cheers
  Andrea
