### ISSUE TITLE
How are redshift bins defined for PrimalCore.tools.extract_pdf ?

### ISSUE THREAD

**Issue by imariasantos** [andreatramacere/primal#6]
The `extract_pdf` function builds an `BinTableHDU` where column `c5` is the redshift grid. Are the redshift bins centered on the values in `c5`, or do those values indicate the edge of a bin?

**Comment by andreatramacere** [comment]
Hi,
1) the grid is defined in eval_pdf_gmm, as np.linspace(grid_min,grid_max,grid_size)
2) if they are set to None, they correspond to min and max values of the z array.
