### ISSUE TITLE
Creating the `randomized_datasets` object for `pdf.tools.extract_pdf`

### ISSUE THREAD

**Issue by imariasantos** [andreatramacere/primal#8]
In order to build PDFs from randomized trials (rather than based on the predictions of each individual estimator), a `randomized_datasets` parameter can be passed to the function `pdf.tools.extract_pdf`. Does Primal include a function to generate a `randomized_datasets`?

**Comment by andreatramacere** [comment]
Hi,
have a look at the function:
`PrimalInteractive.scripts.compare_models_pipeline.randomize_test`
and how it is called in `PrimalInteractive.scripts.compare_models_pipeline`
